/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import Connection.DatabaseCon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HELLO
 */
public class MenuPengembalianUser extends javax.swing.JPanel {
private Connection connect;
private String adaPengembalian = null;
private boolean check = false;
    /**
     * Creates new form MenuPengembalian
     */
    public MenuPengembalianUser() {
        initComponents();
        DatabaseCon data = new DatabaseCon();
        connect = data.getConnection();
        generateIDPengembalian();
        getData();
       
    }
    
    private String generateIDPengembalian() {
        try {
            String code = "PGB";
            String yyMM = new SimpleDateFormat("yyMM").format(new Date());
            String bookID = "";

            String sql = "SELECT COUNT(*) AS jumlah FROM pengembalian";
            Statement stmt = connect.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            int nomor = 1;
            if (rs.next()) {
                nomor = rs.getInt("jumlah") + 1;
            }
            bookID = code + yyMM + String.format("%04d", nomor);
            idKembali.setText(bookID);

            rs.close();
            stmt.close();
            return bookID;

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    private void ProsesPengembalian(){
        if (adaPengembalian == null) {
            adaPengembalian = generateIDPengembalian();
        }
        String idPengembalian = adaPengembalian;
        String idPeminjaman = idPinjam.getText();
        String idBuku = IDBuku.getText();

    try {
        // Ambil tanggal jatuh tempo dari DB
        PreparedStatement getTanggal = connect.prepareStatement("SELECT tanggal_kembali FROM peminjaman WHERE id_peminjaman = ?");
        getTanggal.setString(1, idPeminjaman);
        ResultSet rs = getTanggal.executeQuery();

        if (rs.next()) {
            Date jatuhTempo = rs.getDate("tanggal_kembali");
            LocalDate jatuhTempoLocal = ((java.sql.Date) jatuhTempo).toLocalDate();

            // Ngambil tanggal kembali dari JDateChooser
            Date tglKembalii = tglKembali.getDate(); 
            LocalDate tglKembaliLocal = ((java.sql.Date) new java.sql.Date(tglKembalii.getTime())).toLocalDate();

            // Ngitung selisih hari jatoh tempo sama kembali
            long selisih = ChronoUnit.DAYS.between(jatuhTempoLocal, tglKembaliLocal);
            int denda = (int) Math.max(0, selisih) * 2000;
            
                // Insert pengembalian
                String sql = "INSERT INTO pengembalian (id_pengembalian, id_peminjaman, id_buku, tgl_kembali, denda) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement insert = connect.prepareStatement(sql);
                insert.setString(1, idPengembalian);
                insert.setString(2, idPeminjaman);
                insert.setString(3, idBuku);
                if (tglKembali != null) {
                insert.setDate(4, new java.sql.Date(tglKembalii.getTime()));
                } else {
                    JOptionPane.showMessageDialog(this, "Tanggal kembali belum dipilih!");
                    return;
                }
                insert.setInt(5, denda);
                insert.executeUpdate();
      
                getData();
            
            int pilihan = JOptionPane.showConfirmDialog(this, "Mau kembalikan buku yang lain?", "Tambah Pengembalian Buku", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.NO_OPTION) {
                    adaPengembalian = null;
                    JOptionPane.showMessageDialog(this, "Pengembalian berhasil!\nKamu Dikenakan Denda: Rp" + denda);
                }

        }
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menyimpan pengembalian!");
    }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKembali = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addPinjam = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idKembali = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idPinjam = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        IDBuku = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        totalPinjam = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        pilihAnggota = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableKembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pengembalian", "ID Peminjaman", "ID Buku", "Tanggal Pengembalian", "Status", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKembali.setPreferredSize(new java.awt.Dimension(525, 400));
        tableKembali.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableKembali);
        if (tableKembali.getColumnModel().getColumnCount() > 0) {
            tableKembali.getColumnModel().getColumn(0).setResizable(false);
            tableKembali.getColumnModel().getColumn(1).setResizable(false);
            tableKembali.getColumnModel().getColumn(2).setResizable(false);
            tableKembali.getColumnModel().getColumn(3).setResizable(false);
            tableKembali.getColumnModel().getColumn(4).setResizable(false);
            tableKembali.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 37, 69));
        jLabel4.setText("Transaksi > Pengembalian");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\HELLO\\OneDrive\\Gambar\\Elemen\\Return Book.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 37, 69));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Return Book.png"))); // NOI18N
        jLabel2.setText("Data Pengembalian Buku Inkling's Library");

        add.setText("Add");
        add.setPreferredSize(new java.awt.Dimension(33, 23));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel1, "card2");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Anggota.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Tambah Data Pengembalian");

        addPinjam.setText("Add");
        addPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPinjamActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("ID Pengembalian");

        idKembali.setEditable(false);
        idKembali.setBackground(new java.awt.Color(255, 255, 255));
        idKembali.setForeground(new java.awt.Color(102, 102, 102));
        idKembali.setToolTipText("");
        idKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idKembaliActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("ID Peminjaman");

        idPinjam.setEditable(false);
        idPinjam.setBackground(new java.awt.Color(255, 255, 255));
        idPinjam.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("ID Buku");

        IDBuku.setEditable(false);
        IDBuku.setBackground(new java.awt.Color(255, 255, 255));
        IDBuku.setForeground(new java.awt.Color(0, 0, 0));

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Total Peminjaman");

        totalPinjam.setBackground(new java.awt.Color(255, 255, 255));
        totalPinjam.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add2.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\HELLO\\OneDrive\\Gambar\\Elemen\\User.png")); // NOI18N
        jLabel20.setText("jLabel9");

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(8, 37, 69));
        jLabel21.setText("Data > Anggota");

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Tanggal Pengembalian");

        tglKembali.setBackground(new java.awt.Color(255, 255, 255));
        tglKembali.setMinimumSize(new java.awt.Dimension(72, 12));
        tglKembali.setPreferredSize(new java.awt.Dimension(72, 12));

        pilihAnggota.setText("...");
        pilihAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihAnggotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idKembali, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPinjam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                                        .addComponent(idPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pilihAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(addPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(7, 7, 7)))
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tglKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        mainPanel.add(panelAdd, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pilihAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihAnggotaActionPerformed
        // TODO add your handling code here:
        new PilihPeminjaman(this).setVisible(true);
    }//GEN-LAST:event_pilihAnggotaActionPerformed

    private void idKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idKembaliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(jPanel1);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPinjamActionPerformed
        // TODO add your handling code here:
        ProsesPengembalian();
    }//GEN-LAST:event_addPinjamActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(panelAdd);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDBuku;
    private javax.swing.JButton add;
    private javax.swing.JButton addPinjam;
    private javax.swing.JTextField idKembali;
    private javax.swing.JTextField idPinjam;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JButton pilihAnggota;
    private javax.swing.JTable tableKembali;
    private com.toedter.calendar.JDateChooser tglKembali;
    private javax.swing.JTextField totalPinjam;
    // End of variables declaration//GEN-END:variables

    public void setDataIDPengembalian(String idPinjam1, String idBuku1, String total){
        idPinjam.setText(idPinjam1);
        IDBuku.setText(idBuku1);
        totalPinjam.setText(total);
    }
    
    private void getData() {
        DefaultTableModel model = (DefaultTableModel) tableKembali.getModel();
        model.setRowCount(0);

        try {
            String sqlSelect = "SELECT id_pengembalian, id_peminjaman, id_buku, tgl_kembali, denda, " +
                                "CASE " +
                                "WHEN tgl_kembali >= CURDATE() THEN 'Dikembalikan' " +
                                "WHEN tgl_kembali < CURDATE() THEN 'Terlambat' " +
                                "END AS status " + "FROM pengembalian";
            PreparedStatement stmtSelect = connect.prepareStatement(sqlSelect);
            ResultSet rs = stmtSelect.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pengembalian"),
                    rs.getString("id_peminjaman"),
                    rs.getString("id_buku"),
                    rs.getDate("tgl_kembali"),
                    rs.getString("status"),
                    rs.getInt("denda")
                });
            }

            tableKembali.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mengambil data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
}
}